name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1

    - name: Update submodules
      run: |
        git submodule update --init --recursive

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Black
      run: |
        pip install black
        black --check .
      if: matrix.python-version != '2.7' && matrix.python-version != '3.5'

    - name: Install from source
      run: |
        pip install .

    - name: Run CLI
      run: |
        screenshot-manager --help

    - name: Install from dist
      run: |
        rm -f dist/*.tar.gz
        python setup.py sdist
        pip install dist/*.tar.gz
